base_url: "https://eselizabeth.github.io/inker-example"
webserver_port: "5005"
website_name: "inker"
posts_per_page: "4"
pagination: "false"
icon_path: "icon.png"
template_name: "navy"
generate_nav: "true"
extra:
  - { about.md: "about.html", visible-name: "about" }
headers:
- "Getting started"
- "Configuration"
- "Features"
- "Deployment"